2024-04-10 16:08:40,799 root         INFO      ============================================================================    app_validation_main.py:[75     - main                ()] 
2024-04-10 16:08:40,799 root         INFO      ==> validation (Version: 1.0.1 Release_Date: 2023-07-19)                        app_validation_main.py:[76     - main                ()] 
2024-04-10 16:08:40,799 root         INFO      ==> START ...                                                                   app_validation_main.py:[77     - main                ()] 
2024-04-10 16:08:40,799 root         INFO                                                                                      app_validation_main.py:[78     - main                ()] 
2024-04-10 16:08:40,799 root         INFO      ---> Compute cells list ...                                                     lib_utils_generic.py:[75     - get_grid_cells      ()] 
2024-04-10 16:08:40,799 root         INFO      ----> Use information defined in the settings file ...                          lib_utils_generic.py:[140    - get_grid_cells      ()] 
2024-04-10 16:08:40,799 root         INFO      ----> Use information defined in the settings file ... DONE                     lib_utils_generic.py:[144    - get_grid_cells      ()] 
2024-04-10 16:08:40,799 root         INFO      ---> Compute cells list ... DONE                                                lib_utils_generic.py:[147    - get_grid_cells      ()] 
2024-04-10 16:08:40,800 root         WARNING   ===> SWI option not activated for k2 datasets in the configuration file         drv_process_main.py:[59     - __init__            ()] 
2024-04-10 16:08:40,800 root         INFO      ---> Setup process ...                                                          drv_process_main.py:[129    - setup_process       ()] 
2024-04-10 16:08:40,803 root         INFO      ----> Setup source datasets ...                                                 cpl_process_datasets.py:[67     - setup_datasets_src  ()] 
2024-04-10 16:08:40,803 root         INFO      -----> Datasets "ref" ...                                                       cpl_process_datasets.py:[74     - setup_datasets_src  ()] 
2024-04-10 16:08:41,041 root         WARNING   ===> The obj "args" is not defined in the dataset obj. Use empty list.          cpl_process_datasets.py:[195    - set_dset_arguments  ()] 
2024-04-10 16:08:41,041 root         INFO      -----> Datasets "ref" ... DONE                                                  cpl_process_datasets.py:[105    - setup_datasets_src  ()] 
2024-04-10 16:08:41,041 root         INFO      -----> Datasets "k1" ...                                                        cpl_process_datasets.py:[74     - setup_datasets_src  ()] 
2024-04-10 16:08:41,104 root         WARNING   ===> The obj "args" is not defined in the dataset obj. Use empty list.          cpl_process_datasets.py:[195    - set_dset_arguments  ()] 
2024-04-10 16:08:41,105 root         INFO      -----> Datasets "k1" ... DONE                                                   cpl_process_datasets.py:[105    - setup_datasets_src  ()] 
2024-04-10 16:08:41,105 root         INFO      -----> Datasets "k2" ...                                                        cpl_process_datasets.py:[74     - setup_datasets_src  ()] 
2024-04-10 16:08:41,180 root         WARNING   ===> The obj "args" is not defined in the dataset obj. Use empty list.          cpl_process_datasets.py:[195    - set_dset_arguments  ()] 
2024-04-10 16:08:41,181 root         INFO      -----> Datasets "k2" ... DONE                                                   cpl_process_datasets.py:[105    - setup_datasets_src  ()] 
2024-04-10 16:08:41,181 root         INFO      ----> Setup source datasets ... DONE                                            cpl_process_datasets.py:[108    - setup_datasets_src  ()] 
2024-04-10 16:08:41,181 root         INFO      ----> Setup destination datasets ...                                            cpl_process_datasets.py:[116    - setup_datasets_dst  ()] 
2024-04-10 16:08:41,181 root         INFO      ----> Setup destination datasets ... DONE                                       cpl_process_datasets.py:[133    - setup_datasets_dst  ()] 
2024-04-10 16:08:41,182 root         INFO      ---> Setup process ... DONE                                                     drv_process_main.py:[170    - setup_process       ()] 
2024-04-10 16:08:41,182 root         INFO      ---> Execute process in "sequential" ...                                        drv_process_main.py:[176    - execute_process     ()] 
2024-04-10 16:08:41,183 root         INFO      ----> Execute process ...                                                       drv_process_main.py:[230    - exec_process_wrap   ()] 
2024-04-10 16:08:41,183 root         INFO      ----> Start time "2024-04-10 16:08:41"                                          drv_process_main.py:[231    - exec_process_wrap   ()] 
2024-04-10 16:08:41,183 root         INFO       (1) Process Group: "000"                                                       drv_process_main.py:[232    - exec_process_wrap   ()] 
2024-04-10 16:08:41,183 root         INFO       (2) Process Cell(s): "1357"                                                    drv_process_main.py:[233    - exec_process_wrap   ()] 
2024-04-10 16:08:49,777 root         INFO      -----> Process Info :: IDX: 001 of 720 :: JOB: "(1864463, 5.066604137420654, 35.003822326660156)" :: STEP: 0.14 [%] ...  drv_process_main.py:[260    - exec_process_wrap   ()] 
2024-04-10 16:09:07,836 root         INFO      ------> Read ASCAT time-series for GPI "1864463" ...                            lib_datasets_ascat.py:[310    - read                ()] 
2024-04-10 16:09:07,842 root         INFO      -------> Data valid for ASCAT dataset (N: "677")                                lib_datasets_ascat.py:[412    - read                ()] 
2024-04-10 16:09:07,843 root         INFO      -------> Time valid for ASCAT dataset from "2021-06-01 10:04:01" to "2023-05-30 20:20:00" lib_datasets_ascat.py:[414    - read                ()] 
2024-04-10 16:09:07,843 root         INFO      ------> Read ASCAT time-series for GPI "1864463" ... PREVIOUSLY SAVED           lib_datasets_ascat.py:[417    - read                ()] 
2024-04-10 16:09:55,579 root         INFO      ------> Read GLDAS time-series for GPI "547940" ...                             lib_datasets_gldas.py:[81     - read                ()] 
2024-04-10 16:31:32,488 root         WARNING   ===> Error in reading GLDAS time-series "KeyboardInterrupt()"                   lib_datasets_gldas.py:[156    - read                ()] 
2024-04-10 16:31:32,488 root         WARNING   ===> GLDAS time-series will be initialized by empty dataframe                   lib_datasets_gldas.py:[157    - read                ()] 
2024-04-10 16:31:32,489 root         INFO      ------> Read GLDAS time-series for GPI "547940" ... FAILED                      lib_datasets_gldas.py:[161    - read                ()] 
2024-04-10 16:31:32,489 root         INFO      ------> Read CCI time-series for GPI "316100" ...                               lib_datasets_cci.py:[96     - read                ()] 
2024-04-10 16:31:32,576 root         INFO      -------> Data valid for CCI dataset (N: "1257")                                 lib_datasets_cci.py:[131    - read                ()] 
2024-04-10 16:31:32,576 root         INFO      -------> Time valid for CCI dataset from "2019-06-01 00:00:00" to "2022-12-31 00:00:00" lib_datasets_cci.py:[133    - read                ()] 
2024-04-10 16:31:32,577 root         INFO      ------> Read CCI time-series for GPI "316100" ... DONE                          lib_datasets_cci.py:[140    - read                ()] 
2024-04-10 16:31:32,581 root         ERROR     ===> Datasets are not defined for point "(1864463, 5.066604137420654, 35.003822326660156)": "No temporally matched data for (3, 3) and metric calculator <bound method ExtendedMetrics.calc_metrics of <lib_utils_metrics.ExtendedMetrics object at 0x7f29afaab190>> for gpi (1864463, 5.066604137420654, 35.003822326660156)!" pytesmo_validation_framework.py:[261    - calc                ()] 
2024-04-10 16:31:32,583 root         INFO      ------> Compute metrics ...                                                     lib_utils_metrics.py:[474    - calc_metrics        ()] 
2024-04-10 16:31:32,583 root         INFO      ------> Season "ALL" ...                                                        lib_utils_metrics.py:[486    - calc_metrics        ()] 
2024-04-10 16:31:32,584 root         INFO      -------> Datasets check ...                                                     lib_utils_metrics.py:[841    - check_data          ()] 
2024-04-10 16:31:32,584 root         WARNING   --------> No data in "ref" slice. NO DATA                                       lib_utils_metrics.py:[875    - check_data          ()] 
2024-04-10 16:31:32,584 root         WARNING   --------> No data in "k1" slice. NO DATA                                        lib_utils_metrics.py:[875    - check_data          ()] 
2024-04-10 16:31:32,584 root         WARNING   --------> No data in "k2" slice. NO DATA                                        lib_utils_metrics.py:[875    - check_data          ()] 
2024-04-10 16:31:32,584 root         WARNING   --------> Datasets for this point are not eligible to compute metrics. Skip this point lib_utils_metrics.py:[886    - check_data          ()] 
2024-04-10 16:31:32,584 root         INFO      -------> Datasets check ... FAILED                                              lib_utils_metrics.py:[887    - check_data          ()] 
2024-04-10 16:31:32,584 root         INFO      ------> Season "ALL" ... FAILED                                                 lib_utils_metrics.py:[556    - calc_metrics        ()] 
2024-04-10 16:31:32,585 root         INFO      ------> Compute metrics ... DONE                                                lib_utils_metrics.py:[758    - calc_metrics        ()] 
2024-04-10 16:31:32,604 root         INFO      -----> Process Info :: IDX: 001 of 720 :: JOB: "(1864463, 5.066604137420654, 35.003822326660156)" :: STEP: 0.14 [%] ... DONE drv_process_main.py:[274    - exec_process_wrap   ()] 
2024-04-10 16:31:32,605 root         INFO      -----> Process Info :: IDX: 002 of 720 :: JOB: "(1864467, 5.2035393714904785, 35.003822326660156)" :: STEP: 0.28 [%] ...  drv_process_main.py:[274    - exec_process_wrap   ()] 
2024-04-10 16:31:32,605 root         INFO      ------> Read ASCAT time-series for GPI "1864467" ...                            lib_datasets_ascat.py:[310    - read                ()] 
2024-04-10 16:31:32,605 root         INFO      -------> Get data ...                                                           lib_datasets_ascat.py:[323    - read                ()] 
